export const GrowSkillAPIEndPointPath = {
  UserRoles: "Login/GetUserRole",
  Login: "Login/Login",
  SaveRequestLoginUser: 'Fujimausa/SaveRequestLoginUser',
  VerifyToken: "Fujimausa/VerifyToken",
  ResetPassword: 'Fujimausa/ResetPassword',
  CheckUserForForgetPassword: 'Fujimausa/CheckUserForForgetPassword',
  GetCategories: 'Fujimausa/GetCategories',
  GetProducts: 'Fujimausa/GetProducts',
  GetProductDetail: 'Fujimausa/GetProductDetail',
  getProductWithAategory: 'Fujimausa/GetAdvanceSearchData',
  getClearanceProduct: 'Fujimausa/GetProducts',
  getOrderList: 'Fujimausa/GetOrderList',
  getRelatedProduct: 'Fujimausa/GetReleatedProducts',
  getSeachedData: 'Fujimausa/GetSearchData',
  getNewArrivals: 'Fujimausa/GetNewArrivalProducts',
  getMostRequestedProduct: 'Fujimausa/GetMostRequestedProducts',
  getComparedProducts: 'Fujimausa/CompareProducts',
  getHomePageBanners: 'Fujimausa/GetHomePageBanners',
  getDynamicPages: 'Fujimausa/GetDynamicPages',
  getAccountInformation: 'Fujimausa/GetAccountInformation',
  getGetManufacturers: 'Fujimausa/GetManufacturers',
  getUserInformation: 'Fujimausa/GetUserInformation',
  userChangePassword: 'Fujimausa/ChangePassword',
  UpdateUserInfo: 'Fujimausa/UpdateUserInfo',
  getCategoriesAndLogo:'Fujimausa/GetCategoriesAndLogo',
  UpdateFeedback: 'Fujimausa/SubmitCustomerFeedback',
  getCompanyProfile: 'Fujimausa/GetCompanyProfile',
  getOrderDetail:'Fujimausa/GetOrderDetail',
  manageShoppingList:'Fujimausa/ManageShoppingList',
}
