export const GrowSkillAPIEndPointPath = {
  UserRoles: "Login/GetUserRole",
  Login: "Login/Login",
  SupperAdminLogin: "Login/Adminlogin",
  GetUserByRole: "Admin/GetUserByRole",
  GetContactPageData: "Admin/GetContactPageData",
  GetContactByFilter: "Admin/GetContactByFilter",
  GetExportContacts: "Admin/exportContacts",
  GetUpdateContact: "Admin/GetUpdateContact",
  GetImportContacts: "Contact/GetImportContacts",
  GetProcessImportContacts: "Admin/GetProcessContact",
  GetContactDetails: "Admin/GetContactDetails",
  GetContactActivities: "Admin/GetContactActivities",
  UpdateContactStatus: "Admin/UpdateContactStatus",
  GetDashboardData: "Admin/GetLoadDashboard",
  UpdateUser: "Admin/GetUpdateUser",
  GetUpdateCompanyProfile: "Admin/GetUpdateCompanyProfile",
  GetUploadCompanyLogo: "Admin/uploadCompanyLogo",
  GetCompanyProfile: "Admin/GetCompanyProfile",
  UpdatePassword:  "Admin/GetUpdatePassword",
  UpdatePipeLine:  "Admin/GetUpdatePipeline",
  GetUpdateBulkAssignment:  "Admin/GetUpdateBulkAssignment",
  GetPipelineData:  "Admin/GetPipelineData",
  GetUpdatePipelineStatusByDrag:  "Admin/GetUpdatePipelineStatusByDrag",
  GetUpdateEmailTemplate:  "Admin/GetUpdateEmailTemplate",
  GetEmailTemplates:  "Admin/GetEmailTemplates",
  GetSubscriptions:  "Admin/GetSubscriptions",
  GetUpdateSubscription:  "Admin/GetUpdateSubscription"
}

